[package]
name = "oka_rust_libary"
version = "0.1.0"
authors = ["agajo <madaopc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
